CoffeeBike\OwasysBundle\Entity\Message\MessageI:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        iox:
            type: integer
        ioType:
            type: integer
            column: io_type
        ioVal:
            type: integer
            column: io_val
        intsToSend:
            type: integer
            column: ints_to_send
        intsElapsed:
            type: integer
            column: ints_elapsed
        intsTotal:
            type: integer
            column: ints_total
    lifecycleCallbacks: {  }
