<?php

namespace CoffeeBike\OwasysBundle\Entity\Message;

use Doctrine\ORM\EntityRepository;

/**
 * MessageARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageARepository extends EntityRepository
{
}
